// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace billingOtt.Models.Billing
{
    [Table("accounts")]
    [Index(nameof(AccountNumber), Name = "accounts_account_number_idx")]
    public partial class Account
    {
        public Account()
        {
            Balances = new HashSet<Balance>();
            Invoices = new HashSet<Invoice>();
        }

        [Key]
        [Column("account_number")]
        [StringLength(16)]
        public string AccountNumber { get; set; } = null!;
        [Column("status")]
        public short Status { get; set; }
        /// <summary>
        /// 1 - individual 2- organization 
        /// </summary>
        [Column("person_type")]
        public short PersonType { get; set; }
        [Column("created_at")]
        public Instant CreatedAt { get; set; }
        [Column("updated_at")]
        public Instant? UpdatedAt { get; set; }

        [InverseProperty(nameof(Balance.AccountNumberNavigation))]
        public virtual ICollection<Balance> Balances { get; set; }
        [InverseProperty(nameof(Invoice.AccountNumberNavigation))]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}