// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace billingOtt.Models.Billing
{
    [Table("balances")]
    public partial class Balance
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("service_id")]
        public Guid ServiceId { get; set; }
        [Column("amount")]
        public decimal? Amount { get; set; }
        [Column("created_at")]
        public Instant CreatedAt { get; set; }
        [Column("update_at")]
        public OffsetTime? UpdateAt { get; set; }
        [Column("account_number")]
        [StringLength(16)]
        public string AccountNumber { get; set; } = null!;

        [ForeignKey(nameof(AccountNumber))]
        [InverseProperty(nameof(Account.Balances))]
        public virtual Account AccountNumberNavigation { get; set; } = null!;
        [ForeignKey(nameof(ServiceId))]
        [InverseProperty("Balances")]
        public virtual Service Service { get; set; } = null!;
    }
}