// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace billingOtt.Models.Billing
{
    [Table("invoices")]
    [Index(nameof(Article), Name = "invoices_article_idx")]
    public partial class Invoice
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("account_number")]
        [StringLength(16)]
        public string AccountNumber { get; set; } = null!;
        [Column("service_id")]
        public Guid ServiceId { get; set; }
        [Column("article")]
        [StringLength(20)]
        public string? Article { get; set; }
        [Column("amount")]
        public decimal? Amount { get; set; }
        /// <summary>
        /// 1 - in process 2 - paid 3 - not paid
        /// </summary>
        [Column("state")]
        public short State { get; set; }
        [Column("reason")]
        [StringLength(128)]
        public string? Reason { get; set; }
        [Column("adding", TypeName = "jsonb")]
        public string? Adding { get; set; }
        [Column("created_at")]
        public Instant CreatedAt { get; set; }
        [Column("updated_at")]
        public Instant? UpdatedAt { get; set; }

        [ForeignKey(nameof(AccountNumber))]
        [InverseProperty(nameof(Account.Invoices))]
        public virtual Account AccountNumberNavigation { get; set; } = null!;
        [ForeignKey(nameof(ServiceId))]
        [InverseProperty("Invoices")]
        public virtual Service Service { get; set; } = null!;
    }
}