// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace billingOtt.Models.Billing
{
    [Table("payments")]
    public partial class Payment
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("service_id")]
        public Guid ServiceId { get; set; }
        [Column("state", TypeName = "character varying")]
        public string? State { get; set; }
        /// <summary>
        /// 1 - payme 2- click 3 - upay 4 - bank
        /// </summary>
        [Column("type")]
        public short Type { get; set; }
        [Column("amount")]
        public decimal Amount { get; set; }
        [Column("adding", TypeName = "jsonb")]
        public string? Adding { get; set; }
        [Column("created_at")]
        public Instant CreatedAt { get; set; }
        [Column("updated_at")]
        public Instant? UpdatedAt { get; set; }

        [ForeignKey(nameof(ServiceId))]
        [InverseProperty("Payments")]
        public virtual Service Service { get; set; } = null!;
    }
}