// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace billingOtt.Models.Billing
{
    [Table("services")]
    [Index(nameof(Slug), Name = "services_slug_idx")]
    public partial class Service
    {
        public Service()
        {
            Balances = new HashSet<Balance>();
            Invoices = new HashSet<Invoice>();
            Payments = new HashSet<Payment>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("slug")]
        [StringLength(70)]
        public string Slug { get; set; } = null!;
        [Column("name")]
        [StringLength(70)]
        public string Name { get; set; } = null!;
        [Column("created_at")]
        public Instant CreatedAt { get; set; }
        [Column("updated_at")]
        public Instant? UpdatedAt { get; set; }

        [InverseProperty(nameof(Balance.Service))]
        public virtual ICollection<Balance> Balances { get; set; }
        [InverseProperty(nameof(Invoice.Service))]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [InverseProperty(nameof(Payment.Service))]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}