// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Vdc
{
    [Table("accounts")]
    public partial class Account
    {
        public Account()
        {
            AccountTariffs = new HashSet<AccountTariff>();
        }

        [Key]
        [Column("id")]
        [StringLength(16)]
        public string Id { get; set; } = null!;
        [Column("account_number")]
        [StringLength(16)]
        public string AccountNumber { get; set; } = null!;
        /// <summary>
        /// 1 - individual 2- organization 
        /// </summary>
        [Column("person_type")]
        public short? PersonType { get; set; }
        /// <summary>
        /// 1 - usual 2 - privileged
        /// </summary>
        [Column("type")]
        public short? Type { get; set; }
        /// <summary>
        /// 1 - pre paid 2 - post paid 3 - half paid
        /// </summary>
        [Column("payment_method")]
        public short? PaymentMethod { get; set; }
        /// <summary>
        /// 1 - hourly 2- daily 3- monthly
        /// </summary>
        [Column("period")]
        public short? Period { get; set; }
        [Column("status")]
        public short Status { get; set; }

        [InverseProperty(nameof(AccountTariff.AccountNumberAccountsAccountNumberNavigation))]
        public virtual ICollection<AccountTariff> AccountTariffs { get; set; }
    }
}