// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Vdc
{
    [Table("attributes")]
    public partial class Attribute
    {
        public Attribute()
        {
            AttributeLocales = new HashSet<AttributeLocale>();
            TariffAttributes = new HashSet<TariffAttribute>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("name")]
        [StringLength(70)]
        public string Name { get; set; } = null!;
        [Column("slug")]
        [StringLength(128)]
        public string Slug { get; set; } = null!;
        /// <summary>
        /// 1 - item 2 - option
        /// </summary>
        [Column("type")]
        public short Type { get; set; }
        /// <summary>
        /// 1 - GB 2 - core
        /// </summary>
        [Column("unit")]
        public short? Unit { get; set; }
        [Column("discountable")]
        public bool Discountable { get; set; }
        [Column("step")]
        public int? Step { get; set; }
        [Column("price")]
        public decimal Price { get; set; }
        [Column("max_value")]
        public int? MaxValue { get; set; }
        [Column("min_value")]
        public int? MinValue { get; set; }

        [InverseProperty(nameof(AttributeLocale.Attribute))]
        public virtual ICollection<AttributeLocale> AttributeLocales { get; set; }
        [InverseProperty(nameof(TariffAttribute.AttributeIdAttributes))]
        public virtual ICollection<TariffAttribute> TariffAttributes { get; set; }
    }
}