// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Vdc
{
    [Table("attribute_locales")]
    public partial class AttributeLocale
    {
        [Key]
        [Column("attribute_id")]
        public long AttributeId { get; set; }
        [Key]
        [Column("locale")]
        [StringLength(2)]
        public string Locale { get; set; } = null!;
        [Column("name")]
        [StringLength(70)]
        public string Name { get; set; } = null!;

        [ForeignKey(nameof(AttributeId))]
        [InverseProperty("AttributeLocales")]
        public virtual Attribute Attribute { get; set; } = null!;
    }
}