// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace billingOtt.Models.Vdc
{
    [Table("charges")]
    public partial class Charge
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("account_number")]
        [StringLength(16)]
        public string AccountNumber { get; set; } = null!;
        [Column("tariff_id")]
        public long TariffId { get; set; }
        [Column("amount")]
        public decimal Amount { get; set; }
        [Column("from_at")]
        public Instant FromAt { get; set; }
        [Column("to_at")]
        public Instant ToAt { get; set; }
        [Column("created_at")]
        public Instant CreatedAt { get; set; }
        [Column("updated_at")]
        public Instant UpdatedAt { get; set; }
        [Column("deleted_at")]
        public Instant? DeletedAt { get; set; }
    }
}