// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Vdc
{
    [Table("tariff_attributes")]
    public partial class TariffAttribute
    {
        [Key]
        [Column("tariff_id")]
        public long TariffId { get; set; }
        [Key]
        [Column("attribute_id")]
        public long AttributeId { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }
        [Column("attribute_id_attributes_id")]
        public long AttributeIdAttributesId { get; set; }
        [Column("tarif_id_tariffs_id")]
        public long TarifIdTariffsId { get; set; }

        [ForeignKey(nameof(AttributeIdAttributesId))]
        [InverseProperty(nameof(Attribute.TariffAttributes))]
        public virtual Attribute AttributeIdAttributes { get; set; } = null!;
        [ForeignKey(nameof(TarifIdTariffsId))]
        [InverseProperty(nameof(Tariff.TariffAttributes))]
        public virtual Tariff TarifIdTariffs { get; set; } = null!;
    }
}