// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Ott
{
    [Table("accounts")]
    public partial class Account
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("account_number", TypeName = "character varying")]
        public string AccountNumber { get; set; } = null!;
        [Column("type")]
        public short? Type { get; set; }
        [Column("payment_method")]
        public short? PaymentMethod { get; set; }
        [Column("period")]
        public short? Period { get; set; }
        [Column("status")]
        public short Status { get; set; }
    }
}