// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace billingOtt.Models.Ott
{
    [Table("account_tariffs")]
    public partial class AccountTariff
    {
        [Key]
        [Column("account_number", TypeName = "character varying")]
        public string AccountNumber { get; set; } = null!;
        [Key]
        [Column("tariff_id")]
        public long TariffId { get; set; }
        [Column("is_active")]
        public bool IsActive { get; set; }
        [Column("deactivation_type")]
        public short DeactivationType { get; set; }
        [Column("ends_at")]
        public LocalDateTime? EndsAt { get; set; }
        [Column("account_number_accounts_account_number")]
        public short AccountNumberAccountsAccountNumber { get; set; }
        [Column("tarif_id_tariffs_id")]
        public long TarifIdTariffsId { get; set; }
        /// <summary>
        /// number of days
        /// </summary>
        [Column("period")]
        public int Period { get; set; }

        [ForeignKey(nameof(TarifIdTariffsId))]
        [InverseProperty(nameof(Tariff.AccountTariffs))]
        public virtual Tariff TarifIdTariffs { get; set; } = null!;
    }
}