// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Ott
{
    [Table("categories")]
    public partial class Category
    {
        public Category()
        {
            CategoryLocales = new HashSet<CategoryLocale>();
            Contents = new HashSet<Content>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("status")]
        public short? Status { get; set; }

        [InverseProperty(nameof(CategoryLocale.CategoryIdCategories))]
        public virtual ICollection<CategoryLocale> CategoryLocales { get; set; }
        [InverseProperty(nameof(Content.CategoryIdCategories))]
        public virtual ICollection<Content> Contents { get; set; }
    }
}