// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Ott
{
    [Table("category_locales")]
    public partial class CategoryLocale
    {
        [Key]
        [Column("category_id")]
        public long CategoryId { get; set; }
        [Key]
        [Column("locale")]
        [MaxLength(1)]
        public char Locale { get; set; }
        [Column("name", TypeName = "character varying")]
        public string Name { get; set; } = null!;
        [Column("category_id_categories_id")]
        public long CategoryIdCategoriesId { get; set; }

        [ForeignKey(nameof(CategoryIdCategoriesId))]
        [InverseProperty(nameof(Category.CategoryLocales))]
        public virtual Category CategoryIdCategories { get; set; } = null!;
    }
}