// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Ott
{
    [Table("contents")]
    public partial class Content
    {
        public Content()
        {
            ChannelTariffs = new HashSet<ChannelTariff>();
            ContentLocales = new HashSet<ContentLocale>();
            InverseParentIdContents = new HashSet<Content>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("group_id")]
        public int GroupId { get; set; }
        [Column("category_id")]
        public long? CategoryId { get; set; }
        [Column("logo", TypeName = "character varying")]
        public string? Logo { get; set; }
        [Column("status")]
        public short? Status { get; set; }
        [Column("sort")]
        public int? Sort { get; set; }
        /// <summary>
        /// channel = 1
        /// </summary>
        [Column("type")]
        public short? Type { get; set; }
        [Column("title", TypeName = "character varying")]
        public string? Title { get; set; }
        [Column("group_id_groups_id")]
        public int GroupIdGroupsId { get; set; }
        [Column("category_id_categories_id")]
        public long CategoryIdCategoriesId { get; set; }
        [Column("parent_id")]
        public long? ParentId { get; set; }
        [Column("depth")]
        public int Depth { get; set; }
        [Column("parent_id_contents_id")]
        public long ParentIdContentsId { get; set; }

        [ForeignKey(nameof(CategoryIdCategoriesId))]
        [InverseProperty(nameof(Category.Contents))]
        public virtual Category CategoryIdCategories { get; set; } = null!;
        [ForeignKey(nameof(GroupIdGroupsId))]
        [InverseProperty(nameof(Group.Contents))]
        public virtual Group GroupIdGroups { get; set; } = null!;
        [ForeignKey(nameof(ParentIdContentsId))]
        [InverseProperty(nameof(Content.InverseParentIdContents))]
        public virtual Content ParentIdContents { get; set; } = null!;
        [InverseProperty(nameof(ChannelTariff.ChannelIdChannels))]
        public virtual ICollection<ChannelTariff> ChannelTariffs { get; set; }
        [InverseProperty(nameof(ContentLocale.ContentIdContens))]
        public virtual ICollection<ContentLocale> ContentLocales { get; set; }
        [InverseProperty(nameof(Content.ParentIdContents))]
        public virtual ICollection<Content> InverseParentIdContents { get; set; }
    }
}