// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Ott
{
    [Table("content_locales")]
    public partial class ContentLocale
    {
        [Key]
        [Column("contnet_id")]
        public long ContnetId { get; set; }
        [Key]
        [Column("locale", TypeName = "character varying")]
        public string Locale { get; set; } = null!;
        [Column("name", TypeName = "character varying")]
        public string Name { get; set; } = null!;
        [Column("description")]
        public string? Description { get; set; }
        [Column("link")]
        public string? Link { get; set; }
        [Column("content_id_contens_id")]
        public long ContentIdContensId { get; set; }

        [ForeignKey(nameof(ContentIdContensId))]
        [InverseProperty(nameof(Content.ContentLocales))]
        public virtual Content ContentIdContens { get; set; } = null!;
    }
}