// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Ott
{
    [Table("groups")]
    public partial class Group
    {
        public Group()
        {
            Contents = new HashSet<Content>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(70)]
        public string? Name { get; set; }
        [Column("slug")]
        [StringLength(70)]
        public string? Slug { get; set; }

        [InverseProperty(nameof(Content.GroupIdGroups))]
        public virtual ICollection<Content> Contents { get; set; }
    }
}