// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Ott
{
    [Table("tariffs")]
    public partial class Tariff
    {
        public Tariff()
        {
            AccountTariffs = new HashSet<AccountTariff>();
            ChannelTariffs = new HashSet<ChannelTariff>();
            TariffLocales = new HashSet<TariffLocale>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("name", TypeName = "character varying")]
        public string? Name { get; set; }
        [Column("sum")]
        public decimal? Sum { get; set; }
        [Column("type")]
        public short? Type { get; set; }

        [InverseProperty(nameof(AccountTariff.TarifIdTariffs))]
        public virtual ICollection<AccountTariff> AccountTariffs { get; set; }
        [InverseProperty(nameof(ChannelTariff.TariffIdTariffs))]
        public virtual ICollection<ChannelTariff> ChannelTariffs { get; set; }
        [InverseProperty(nameof(TariffLocale.TariffIdTariffs))]
        public virtual ICollection<TariffLocale> TariffLocales { get; set; }
    }
}