// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace billingOtt.Models.Ott
{
    [Table("tariff_locales")]
    public partial class TariffLocale
    {
        [Key]
        [Column("tariff_id")]
        public long TariffId { get; set; }
        [Key]
        [Column("locale", TypeName = "character varying")]
        public string Locale { get; set; } = null!;
        [Column("name", TypeName = "character varying")]
        public string Name { get; set; } = null!;
        [Column("tariff_id_tariffs_id")]
        public long TariffIdTariffsId { get; set; }

        [ForeignKey(nameof(TariffIdTariffsId))]
        [InverseProperty(nameof(Tariff.TariffLocales))]
        public virtual Tariff TariffIdTariffs { get; set; } = null!;
    }
}